# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory remotetime
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	_ExactTimeStub.class \
	ExactTime.class \
	ExactTimeHolder.class \
	ExactTimeHelper.class \
	_ExactTimeImplBase.class


_ExactTimeStub.class : _ExactTimeStub.java
ExactTime.class : ExactTime.java
ExactTimeHolder.class : ExactTimeHolder.java
ExactTimeHelper.class : ExactTimeHelper.java
_ExactTimeImplBase.class : _ExactTimeImplBase.java
