# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c10
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	ExceptionMethods.class \
	Rethrowing.class \
	ThrowOut.class \
	RethrowNew.class \
	NeverCaught.class \
	Inheriting.class \
	Inheriting2.class \
	SimpleException.class \
	StormyInning.class \
	FinallyWorks.class \
	Switch.class \
	OnOffSwitch.class \
	WithFinally.class \
	AlwaysFinally.class \
	LostMessage.class \
	Cleanup.class \
	Human.class


ExceptionMethods.class: ExceptionMethods.java
Rethrowing.class: Rethrowing.java
ThrowOut.class: ThrowOut.java
RethrowNew.class: RethrowNew.java
NeverCaught.class: NeverCaught.java
Inheriting.class: Inheriting.java
Inheriting2.class: Inheriting2.java
SimpleException.class: SimpleException.java
StormyInning.class: StormyInning.java
FinallyWorks.class: FinallyWorks.java
Switch.class: Switch.java
OnOffSwitch.class: OnOffSwitch.java
WithFinally.class: WithFinally.java
AlwaysFinally.class: AlwaysFinally.java
LostMessage.class: LostMessage.java
Cleanup.class: Cleanup.java
Human.class: Human.java
