# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c15\rmi
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	PerfectTimeI.class \
	PerfectTime.class \
	DisplayPerfectTime.class


PerfectTimeI.class: PerfectTimeI.java
PerfectTime.class: PerfectTime.java
DisplayPerfectTime.class: DisplayPerfectTime.java
