# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c13
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	Applet1.class \
	Applet1b.class \
	Applet1c.class \
	Applet1d.class \
	Button1.class \
	Button2.class \
	Button2b.class \
	TextField1.class \
	TextArea1.class \
	Label1.class \
	CheckBox1.class \
	RadioButton1.class \
	Choice1.class \
	List1.class \
	TabbedPane1.class \
	MessageBoxes.class \
	SimpleMenus.class \
	DialogDemo.class \
	FlowLayout1.class \
	BorderLayout1.class \
	GridLayout1.class \
	BoxLayout1.class \
	Box1.class \
	Box2.class \
	Box3.class \
	Box4.class \
	TrackEvent.class \
	ButtonApp.class \
	Menu1.class \
	TicTacToe.class \
	FileChooserTest.class \
	Button2New.class \
	Applet3.class \
	TextNew.class \
	TextAreaNew.class \
	RadioCheckNew.class \
	ChoiceNew.class \
	ListNew.class \
	MenuNew.class \
	TicTacToeInner.class \
	LookAndFeel.class \
	DynamicEvents.class \
	Separation.class \
	GoodIdea.class \
	CutAndPaste.class \
	BeanDumper.class \
	ButtonDemo.class \
	Borders.class \
	Buttons.class \
	ButtonGroups.class \
	Faces.class \
	Menus.class \
	Popup.class \
	ListCombo.class \
	Progress.class \
	Trees.class \
	Table.class \
	ShowHTML.class \
	Fetcher.class \
	DisplayMethods.class


Applet1.class: Applet1.java
Applet1b.class: Applet1b.java
Applet1c.class: Applet1c.java
Applet1d.class: Applet1d.java
Button1.class: Button1.java
Button2.class: Button2.java
Button2b.class: Button2b.java
TextField1.class: TextField1.java
TextArea1.class: TextArea1.java
Label1.class: Label1.java
CheckBox1.class: CheckBox1.java
RadioButton1.class: RadioButton1.java
Choice1.class: Choice1.java
List1.class: List1.java
TabbedPane1.class: TabbedPane1.java
MessageBoxes.class: MessageBoxes.java
SimpleMenus.class: SimpleMenus.java
DialogDemo.class: DialogDemo.java
FlowLayout1.class: FlowLayout1.java
BorderLayout1.class: BorderLayout1.java
GridLayout1.class: GridLayout1.java
BoxLayout1.class: BoxLayout1.java
Box1.class: Box1.java
Box2.class: Box2.java
Box3.class: Box3.java
Box4.class: Box4.java
TrackEvent.class: TrackEvent.java
ButtonApp.class: ButtonApp.java
Menu1.class: Menu1.java
TicTacToe.class: TicTacToe.java
FileChooserTest.class: FileChooserTest.java
Button2New.class: Button2New.java
Applet3.class: Applet3.java
TextNew.class: TextNew.java
TextAreaNew.class: TextAreaNew.java
RadioCheckNew.class: RadioCheckNew.java
ChoiceNew.class: ChoiceNew.java
ListNew.class: ListNew.java
MenuNew.class: MenuNew.java
TicTacToeInner.class: TicTacToeInner.java
LookAndFeel.class: LookAndFeel.java
DynamicEvents.class: DynamicEvents.java
Separation.class: Separation.java
GoodIdea.class: GoodIdea.java
CutAndPaste.class: CutAndPaste.java
BeanDumper.class: BeanDumper.java
ButtonDemo.class: ButtonDemo.java
Borders.class: Borders.java
Buttons.class: Buttons.java
ButtonGroups.class: ButtonGroups.java
Faces.class: Faces.java
Menus.class: Menus.java
Popup.class: Popup.java
ListCombo.class: ListCombo.java
Progress.class: Progress.java
Trees.class: Trees.java
Table.class: Table.java
ShowHTML.class: ShowHTML.java
Fetcher.class: Fetcher.java
DisplayMethods.class: DisplayMethods.java
