# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c05
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	LibTest.class \
	ToolTest.class \
	TestAssert.class \
	Dinner.class \
	Cake.class \
	Pie.class \
	IceCream.class \
	ChocolateChip.class \
	Lunch.class


LibTest.class: LibTest.java
ToolTest.class: ToolTest.java
TestAssert.class: TestAssert.java
Dinner.class: Dinner.java
Cake.class: Cake.java
Pie.class: Pie.java
IceCream.class: IceCream.java
ChocolateChip.class: ChocolateChip.java
Lunch.class: Lunch.java
