# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c15\ejb
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	PerfectTime.class \
	PerfectTimeHome.class \
	PerfectTimeBean.class \
	PerfectTimeClient.class


PerfectTime.class: PerfectTime.java
	echo You must install the J2EE Java Enterprise Edition from java.sun.com and add j2ee.jar to your CLASSPATH in order to compile this file. See details at java.sun.com.
	javac PerfectTime.java
PerfectTimeHome.class: PerfectTimeHome.java
PerfectTimeBean.class: PerfectTimeBean.java
PerfectTimeClient.class: PerfectTimeClient.java
