# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c15
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	WhoAmI.class \
	JabberServer.class \
	JabberClient.class \
	MultiJabberServer.class \
	MultiJabberClient.class \
	ShowHTML.class \
	Fetcher.class


WhoAmI.class: WhoAmI.java
JabberServer.class: JabberServer.java
JabberClient.class: JabberClient.java
MultiJabberServer.class: MultiJabberServer.java
MultiJabberClient.class: MultiJabberClient.java
ShowHTML.class: ShowHTML.java
Fetcher.class: Fetcher.java
