# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c04
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	SimpleConstructor.class \
	SimpleConstructor2.class \
	Overloading.class \
	OverloadingOrder.class \
	PrimitiveOverloading.class \
	Demotion.class \
	DefaultConstructor.class \
	Leaf.class \
	Flower.class \
	Garbage.class \
	DeathCondition.class \
	InitialValues.class \
	OrderOfInitialization.class \
	StaticInitialization.class \
	ExplicitStatic.class \
	Mugs.class \
	Arrays.class \
	ArrayNew.class \
	ArrayClassObj.class \
	ArrayInit.class \
	VarArgs.class \
	MultiDimArray.class


SimpleConstructor.class: SimpleConstructor.java
SimpleConstructor2.class: SimpleConstructor2.java
Overloading.class: Overloading.java
OverloadingOrder.class: OverloadingOrder.java
PrimitiveOverloading.class: PrimitiveOverloading.java
Demotion.class: Demotion.java
DefaultConstructor.class: DefaultConstructor.java
Leaf.class: Leaf.java
Flower.class: Flower.java
Garbage.class: Garbage.java
DeathCondition.class: DeathCondition.java
InitialValues.class: InitialValues.java
OrderOfInitialization.class: OrderOfInitialization.java
StaticInitialization.class: StaticInitialization.java
ExplicitStatic.class: ExplicitStatic.java
Mugs.class: Mugs.java
Arrays.class: Arrays.java
ArrayNew.class: ArrayNew.java
ArrayClassObj.class: ArrayClassObj.java
ArrayInit.class: ArrayInit.java
VarArgs.class: VarArgs.java
MultiDimArray.class: MultiDimArray.java
