# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c15\servlets
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	ServletsRule.class \
	EchoForm.class \
	ThreadServlet.class \
	SessionPeek.class
	copy *.class C:\ProgTools\java\tomcat\examples\WEB-INF\classes


ServletsRule.class: ServletsRule.java
EchoForm.class: EchoForm.java
ThreadServlet.class: ThreadServlet.java
SessionPeek.class: SessionPeek.java
