# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c06
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	SprinklerSystem.class \
	Bath.class \
	Detergent.class \
	Cartoon.class \
	Chess.class \
	PlaceSetting.class \
	CADSystem.class \
	Hide.class \
	Car.class \
	Orc.class \
	Wind.class \
	FinalData.class \
	BlankFinal.class \
	FinalArguments.class \
	FinalOverridingIllusion.class \
	Jurassic.class \
	Beetle.class


SprinklerSystem.class: SprinklerSystem.java
Bath.class: Bath.java
Detergent.class: Detergent.java
Cartoon.class: Cartoon.java
Chess.class: Chess.java
PlaceSetting.class: PlaceSetting.java
CADSystem.class: CADSystem.java
Hide.class: Hide.java
Car.class: Car.java
Orc.class: Orc.java
Wind.class: Wind.java
FinalData.class: FinalData.java
BlankFinal.class: BlankFinal.java
FinalArguments.class: FinalArguments.java
FinalOverridingIllusion.class: FinalOverridingIllusion.java
Jurassic.class: Jurassic.java
Beetle.class: Beetle.java
