# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c14
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	Counter1.class \
	SimpleThread.class \
	Counter2.class \
	Counter3.class \
	Counter4.class \
	Daemons.class \
	Sharing1.class \
	Sharing2.class \
	BangBean2.class \
	Blocking.class \
	Interrupt.class \
	Suspend.class \
	Counter5.class \
	TestAccess.class \
	ThreadGroup1.class \
	ColorBoxes.class \
	ColorBoxes2.class


Counter1.class: Counter1.java
SimpleThread.class: SimpleThread.java
Counter2.class: Counter2.java
Counter3.class: Counter3.java
Counter4.class: Counter4.java
Daemons.class: Daemons.java
Sharing1.class: Sharing1.java
Sharing2.class: Sharing2.java
BangBean2.class: BangBean2.java
Blocking.class: Blocking.java
Interrupt.class: Interrupt.java
Suspend.class: Suspend.java
Counter5.class: Counter5.java
TestAccess.class: TestAccess.java
ThreadGroup1.class: ThreadGroup1.java
ColorBoxes.class: ColorBoxes.java
ColorBoxes2.class: ColorBoxes2.java
