# Master makefile for Thinking in Java, 2nd Ed. by Bruce Eckel
# at http://www.BruceEckel.com
# Compiles all the code in the book
# Using the JDK 1.2 compiler
# Copyright notice in Copyright.txt

help: 
	@echo To compile all programs from 
	@echo Thinking in Java, 2nd Edition, type
	@echo one of the following commands,
	@echo according to your platform:
	@echo make dos
	@echo make linux
	@echo
	@echo Make sure that this directory and '.' are
	@echo in your CLASSPATH before compiling

dos:
	cd remotetime
	make
	cd ..
	cd .\appendixa
	make
	cd ..
	cd .\appendixb
	make
	cd ..
	cd .\bangbean
	make
	cd ..
	cd .\c02
	make
	cd ..
	cd .\c03
	make
	cd ..
	cd .\c04
	make
	cd ..
	cd .\c05
	make
	cd ..
	cd .\c05\dessert
	make
	cd ..
	cd ..
	cd .\c06
	make
	cd ..
	cd .\c07
	make
	cd ..
	cd .\c07\music
	make
	cd ..
	cd ..
	cd .\c07\music2
	make
	cd ..
	cd ..
	cd .\c07\music3
	make
	cd ..
	cd ..
	cd .\c07\music4
	make
	cd ..
	cd ..
	cd .\c08
	make
	cd ..
	cd .\c08\controller
	make
	cd ..
	cd ..
	cd .\c08\music5
	make
	cd ..
	cd ..
	cd .\c09
	make
	cd ..
	cd .\c10
	make
	cd ..
	cd .\c11
	make
	cd ..
	cd .\c11\xfiles
	make
	cd ..
	cd ..
	cd .\c12
	make
	cd ..
	cd .\c13
	make
	cd ..
	cd .\c14
	make
	cd ..
	cd .\c15
	make
	cd ..
	cd .\c15\corba
	make
	cd ..
	cd ..
	cd .\c15\ejb
	make
	cd ..
	cd ..
	cd .\c15\jdbc
	make
	cd ..
	cd ..
	cd .\c15\jsp
	make
	cd ..
	cd ..
	cd .\c15\rmi
	make
	cd ..
	cd ..
	cd .\c15\servlets
	make
	cd ..
	cd ..
	cd .\com\bruceeckel\simple
	make
	cd ..
	cd ..
	cd ..
	cd .\com\bruceeckel\swing
	make
	cd ..
	cd ..
	cd ..
	cd .\com\bruceeckel\tools
	make
	cd ..
	cd ..
	cd ..
	cd .\com\bruceeckel\tools\debug
	make
	cd ..
	cd ..
	cd ..
	cd ..
	cd .\com\bruceeckel\util
	make
	cd ..
	cd ..
	cd ..
	cd .\frogbean
	make
	cd ..
	jar cfm BangBean.jar BangBean.mf bangbean

linux: 
	cd remotetime; make
	cd appendixb; make linux
	cd appendixa; make
	cd bangbean; make
	cd c02; make
	cd c03; make
	cd c04; make
	cd c05; make
	cd c05/dessert; make
	cd c06; make
	cd c07; make
	cd c07/music; make
	cd c07/music2; make
	cd c07/music3; make
	cd c07/music4; make
	cd c08; make
	cd c08/controller; make
	cd c08/music5; make
	cd c09; make
	cd c10; make
	cd c11; make
	cd c11/xfiles; make
	cd c12; make
	cd c13; make
	cd c14; make
	cd c15; make
	cd c15/corba; make
	cd c15/ejb; make
	cd c15/jdbc; make
	cd c15/jsp; make
	cd c15/rmi; make
	cd c15/servlets; make
	cd com/bruceeckel/simple; make
	cd com/bruceeckel/swing; make
	cd com/bruceeckel/tools; make
	cd com/bruceeckel/tools/debug; make
	cd com/bruceeckel/util; make
	cd frogbean; make
	jar cfm BangBean.jar BangBean.mf bangbean