# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\appendixa
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	PassReferences.class \
	Alias1.class \
	Alias2.class \
	Cloning.class \
	LocalCopy.class \
	Snake.class \
	DeepCopy.class \
	AddingClone.class \
	Compete.class \
	HorrorFlick.class \
	CheckCloneable.class \
	CopyConstructor.class \
	ImmutableInteger.class \
	MutableInteger.class \
	Immutable1.class \
	Immutable2.class \
	Stringer.class \
	ImmutableStrings.class


PassReferences.class: PassReferences.java
Alias1.class: Alias1.java
Alias2.class: Alias2.java
Cloning.class: Cloning.java
LocalCopy.class: LocalCopy.java
Snake.class: Snake.java
DeepCopy.class: DeepCopy.java
AddingClone.class: AddingClone.java
Compete.class: Compete.java
HorrorFlick.class: HorrorFlick.java
CheckCloneable.class: CheckCloneable.java
CopyConstructor.class: CopyConstructor.java
ImmutableInteger.class: ImmutableInteger.java
MutableInteger.class: MutableInteger.java
Immutable1.class: Immutable1.java
Immutable2.class: Immutable2.java
Stringer.class: Stringer.java
ImmutableStrings.class: ImmutableStrings.java
