# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c15\jdbc
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	Lookup.class \
	VLookup.class \
	CIDConnect.class \
	CIDSQL.class \
	CIDCreateTables.class \
	LoadDB.class


Lookup.class: Lookup.java
VLookup.class: VLookup.java
CIDConnect.class: CIDConnect.java
CIDSQL.class: CIDSQL.java
CIDCreateTables.class: CIDCreateTables.java
LoadDB.class: LoadDB.java
