# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c13
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	Applet1.class \
	Applet1b.class \
	Applet1c.class \
	Applet1d.class \
	Button1.class \
	Button2.class \
	Button2b.class \
	TextArea.class \
	BorderLayout1.class \
	FlowLayout1.class \
	GridLayout1.class \
	BoxLayout1.class \
	Box1.class \
	Box2.class \
	Box3.class \
	Box4.class \
	ShowAddListeners.class \
	TrackEvent.class \
	Buttons.class \
	ButtonGroups.class \
	Faces.class \
	TextFields.class \
	Borders.class \
	JScrollPanes.class \
	TextPane.class \
	CheckBoxes.class \
	RadioButtons.class \
	ComboBoxes.class \
	List.class \
	TabbedPane1.class \
	MessageBoxes.class \
	SimpleMenus.class \
	Menus.class \
	Popup.class \
	SineWave.class \
	Dialogs.class \
	TicTacToe.class \
	FileChooserTest.class \
	HTMLButton.class \
	Progress.class \
	Trees.class \
	Table.class \
	LookAndFeel.class \
	CutAndPaste.class \
	DynamicEvents.class \
	Separation.class \
	BeanDumper.class \
	BangBeanTest.class


Applet1.class: Applet1.java
Applet1b.class: Applet1b.java
Applet1c.class: Applet1c.java
Applet1d.class: Applet1d.java
Button1.class: Button1.java
Button2.class: Button2.java
Button2b.class: Button2b.java
TextArea.class: TextArea.java
BorderLayout1.class: BorderLayout1.java
FlowLayout1.class: FlowLayout1.java
GridLayout1.class: GridLayout1.java
BoxLayout1.class: BoxLayout1.java
Box1.class: Box1.java
Box2.class: Box2.java
Box3.class: Box3.java
Box4.class: Box4.java
ShowAddListeners.class: ShowAddListeners.java
TrackEvent.class: TrackEvent.java
Buttons.class: Buttons.java
ButtonGroups.class: ButtonGroups.java
Faces.class: Faces.java
TextFields.class: TextFields.java
Borders.class: Borders.java
JScrollPanes.class: JScrollPanes.java
TextPane.class: TextPane.java
CheckBoxes.class: CheckBoxes.java
RadioButtons.class: RadioButtons.java
ComboBoxes.class: ComboBoxes.java
List.class: List.java
TabbedPane1.class: TabbedPane1.java
MessageBoxes.class: MessageBoxes.java
SimpleMenus.class: SimpleMenus.java
Menus.class: Menus.java
Popup.class: Popup.java
SineWave.class: SineWave.java
Dialogs.class: Dialogs.java
TicTacToe.class: TicTacToe.java
FileChooserTest.class: FileChooserTest.java
HTMLButton.class: HTMLButton.java
Progress.class: Progress.java
Trees.class: Trees.java
Table.class: Table.java
LookAndFeel.class: LookAndFeel.java
CutAndPaste.class: CutAndPaste.java
DynamicEvents.class: DynamicEvents.java
Separation.class: Separation.java
BeanDumper.class: BeanDumper.java
BangBeanTest.class: BangBeanTest.java
