# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c03
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	Assignment.class \
	PassObject.class \
	MathOps.class \
	AutoInc.class \
	Equivalence.class \
	EqualsMethod.class \
	EqualsMethod2.class \
	Bool.class \
	ShortCircuit.class \
	URShift.class \
	BitManipulation.class \
	Literals.class \
	AllOps.class \
	Overflow.class \
	IfElse.class \
	IfElse2.class \
	WhileTest.class \
	ListCharacters.class \
	CommaOperator.class \
	BreakAndContinue.class \
	LabeledFor.class \
	LabeledWhile.class \
	VowelsAndConsonants.class \
	CastingNumbers.class \
	RandomBounds.class


Assignment.class: Assignment.java
PassObject.class: PassObject.java
MathOps.class: MathOps.java
AutoInc.class: AutoInc.java
Equivalence.class: Equivalence.java
EqualsMethod.class: EqualsMethod.java
EqualsMethod2.class: EqualsMethod2.java
Bool.class: Bool.java
ShortCircuit.class: ShortCircuit.java
URShift.class: URShift.java
BitManipulation.class: BitManipulation.java
Literals.class: Literals.java
AllOps.class: AllOps.java
Overflow.class: Overflow.java
IfElse.class: IfElse.java
IfElse2.class: IfElse2.java
WhileTest.class: WhileTest.java
ListCharacters.class: ListCharacters.java
CommaOperator.class: CommaOperator.java
BreakAndContinue.class: BreakAndContinue.java
LabeledFor.class: LabeledFor.java
LabeledWhile.class: LabeledWhile.java
VowelsAndConsonants.class: VowelsAndConsonants.java
CastingNumbers.class: CastingNumbers.java
RandomBounds.class: RandomBounds.java
