# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c09
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	ArraySize.class \
	IceCream.class \
	TestArrays2.class \
	FillingArrays.class \
	CopyingArrays.class \
	ComparingArrays.class \
	CompType.class \
	Reverse.class \
	ComparatorTest.class \
	StringSorting.class \
	AlphabeticSorting.class \
	ArraySearching.class \
	AlphabeticSearch.class \
	PrintingContainers.class \
	FillingLists.class \
	FillTest.class \
	Cat.class \
	Dog.class \
	CatsAndDogs.class \
	Mouse.class \
	WorksAnyway.class \
	MouseList.class \
	MouseListTest.class \
	CatsAndDogs2.class \
	HamsterMaze.class \
	InfiniteRecursion.class \
	SimpleCollection.class \
	Collection1.class \
	List1.class \
	StackL.class \
	Queue.class \
	Set1.class \
	Set2.class \
	Map1.class \
	Statistics.class \
	SpringDetector.class \
	SpringDetector2.class \
	MPair.class \
	SlowMap.class \
	SimpleHashMap.class \
	StringHashCode.class \
	CountedString.class \
	References.class \
	CanonicalMapping.class \
	Iterators2.class \
	ListPerformance.class \
	SetPerformance.class \
	MapPerformance.class \
	ListSortSearch.class \
	ReadOnly.class \
	Synchronization.class \
	FailFast.class \
	Unsupported.class \
	Enumerations.class \
	Stacks.class \
	Bits.class


ArraySize.class: ArraySize.java
IceCream.class: IceCream.java
TestArrays2.class: TestArrays2.java
FillingArrays.class: FillingArrays.java
CopyingArrays.class: CopyingArrays.java
ComparingArrays.class: ComparingArrays.java
CompType.class: CompType.java
Reverse.class: Reverse.java
ComparatorTest.class: ComparatorTest.java
StringSorting.class: StringSorting.java
AlphabeticSorting.class: AlphabeticSorting.java
ArraySearching.class: ArraySearching.java
AlphabeticSearch.class: AlphabeticSearch.java
PrintingContainers.class: PrintingContainers.java
FillingLists.class: FillingLists.java
FillTest.class: FillTest.java
Cat.class: Cat.java
Dog.class: Dog.java
CatsAndDogs.class: CatsAndDogs.java
Mouse.class: Mouse.java
WorksAnyway.class: WorksAnyway.java
MouseList.class: MouseList.java
MouseListTest.class: MouseListTest.java
CatsAndDogs2.class: CatsAndDogs2.java
HamsterMaze.class: HamsterMaze.java
InfiniteRecursion.class: InfiniteRecursion.java
SimpleCollection.class: SimpleCollection.java
Collection1.class: Collection1.java
List1.class: List1.java
StackL.class: StackL.java
Queue.class: Queue.java
Set1.class: Set1.java
Set2.class: Set2.java
Map1.class: Map1.java
Statistics.class: Statistics.java
SpringDetector.class: SpringDetector.java
SpringDetector2.class: SpringDetector2.java
MPair.class: MPair.java
SlowMap.class: SlowMap.java
SimpleHashMap.class: SimpleHashMap.java
StringHashCode.class: StringHashCode.java
CountedString.class: CountedString.java
References.class: References.java
CanonicalMapping.class: CanonicalMapping.java
Iterators2.class: Iterators2.java
ListPerformance.class: ListPerformance.java
SetPerformance.class: SetPerformance.java
MapPerformance.class: MapPerformance.java
ListSortSearch.class: ListSortSearch.java
ReadOnly.class: ReadOnly.java
Synchronization.class: Synchronization.java
FailFast.class: FailFast.java
Unsupported.class: Unsupported.java
Enumerations.class: Enumerations.java
Stacks.class: Stacks.java
Bits.class: Bits.java
