# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c12
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	Shapes.class \
	SweetShop.class \
	Pets.class \
	PetCount.class \
	PetCount2.class \
	PetCount3.class \
	FamilyVsExactType.class \
	ToyTest.class \
	ShowMethods.class \
	ShowMethodsClean.class


Shapes.class: Shapes.java
SweetShop.class: SweetShop.java
Pets.class: Pets.java
PetCount.class: PetCount.java
PetCount2.class: PetCount2.java
PetCount3.class: PetCount3.java
FamilyVsExactType.class: FamilyVsExactType.java
ToyTest.class: ToyTest.java
ShowMethods.class: ShowMethods.java
ShowMethodsClean.class: ShowMethodsClean.java
