# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c11
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	DirList.class \
	DirList2.class \
	DirList3.class \
	MakeDirectories.class \
	IOStreamDemo.class \
	TestEOF.class \
	Echo.class \
	SortedWordCount.class \
	AnalyzeSentence.class \
	NewIODemo.class \
	IOBug.class \
	Redirecting.class \
	ZipCompress.class \
	ZipCompress.class \
	Worm.class \
	Alien.class \
	FreezeAlien.class \
	Blips.class \
	Blip3.class \
	Logon.class \
	SerialCtl.class \
	MyWorld.class \
	CADState.class \
	ClassScanner.class


DirList.class: DirList.java
DirList2.class: DirList2.java
DirList3.class: DirList3.java
MakeDirectories.class: MakeDirectories.java
IOStreamDemo.class: IOStreamDemo.java
TestEOF.class: TestEOF.java
Echo.class: Echo.java
SortedWordCount.class: SortedWordCount.java
AnalyzeSentence.class: AnalyzeSentence.java
NewIODemo.class: NewIODemo.java
IOBug.class: IOBug.java
Redirecting.class: Redirecting.java
ZipCompress.class: ZipCompress.java
ZipCompress.class: ZipCompress.java
Worm.class: Worm.java
Alien.class: Alien.java
FreezeAlien.class: FreezeAlien.java
Blips.class: Blips.java
Blip3.class: Blip3.java
Logon.class: Logon.java
SerialCtl.class: SerialCtl.java
MyWorld.class: MyWorld.java
CADState.class: CADState.java
ClassScanner.class: ClassScanner.java
