# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\com\bruceeckel\util
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	Generator.class \
	BooleanGenerator.class \
	ByteGenerator.class \
	CharGenerator.class \
	ShortGenerator.class \
	IntGenerator.class \
	LongGenerator.class \
	FloatGenerator.class \
	DoubleGenerator.class \
	Arrays2.class \
	AlphabeticComparator.class \
	Pair.class \
	MapGenerator.class \
	Collections2.class \
	CountryCapitals.class \
	StripQualifiers.class


Generator.class: Generator.java
BooleanGenerator.class: BooleanGenerator.java
ByteGenerator.class: ByteGenerator.java
CharGenerator.class: CharGenerator.java
ShortGenerator.class: ShortGenerator.java
IntGenerator.class: IntGenerator.java
LongGenerator.class: LongGenerator.java
FloatGenerator.class: FloatGenerator.java
DoubleGenerator.class: DoubleGenerator.java
Arrays2.class: Arrays2.java
AlphabeticComparator.class: AlphabeticComparator.java
Pair.class: Pair.java
MapGenerator.class: MapGenerator.java
Collections2.class: Collections2.java
CountryCapitals.class: CountryCapitals.java
StripQualifiers.class: StripQualifiers.java
